name: Tencent-Cloud-CDN-Push-Paths-Cache
description: This action purges paths cache for Tencent Cloud CDN via Node SDK API.
branding:
  icon: refresh-ccw
  color: green
inputs:
  secret_id:
    description: The secretId used to authenticate with Tencent Cloud.
    required: true
  secret_key:
    description: The accessKeySecret used to authenticate with Tencent Cloud.
    required: true
  Urls:
    description: "Directory listing, needs to include protocol header http: or https:"
    required: true
  UrlEncode:
    description: "url encode"
    required: false
  Area:
    description: "mainland or overseas"
    required: false
  UserAgent:
    description: "request User-Agent, default: TencentCdn"
    required: false
  Layer:
    description: "default: middle"
    required: false

runs:
  using: node20
  main: bootstrap.mjs
