name: ✅ test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          ref: ${{ github.ref }}

      # default test
      - uses: ./
        with:
          Urls: |
            https://test.ksh7.com/
          secret_id: ${{secrets.TENCENT_CDN_CACHE_SECRET_ID}}
          secret_key: ${{secrets.TENCENT_CDN_CACHE_SECRET_KEY}}

  test-passing:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
